### ISSUE TITLE
Databases

### ISSUE THREAD

**Issue by DanielRivasMD** [nimarafati/Rabbit_Domestication_Brain_RNA_Seq#1]
Hi,

I cannot find the Database S4 anywhere. Could you share? Appreciated.

**Comment by daikisato12** [comment]
Hi @DanielRivasMD ,

Sorry for my late response. The Database S1–4 are included in the zipped supplementary files, which you can download from the journal website: https://academic.oup.com/gbe/advance-article/doi/10.1093/gbe/evaa158/5896528) 

Best regards,

Daiki

**Comment by nimarafati** [comment]
Hi @DanielRivasMD ,

We have now uploaded databases on github repository as well. You can find the databases under data/rawdata folder.

Best regards,
Nia
